xinganr/myapp/views/picture.py
#!/usr/bin/env python
#-*-coding:utf-8-*-
from flask import Blueprint, render_template, g
from myapp.models import *

pictureapp=Blueprint("picture",__name__,static_folder='static',template_folder='templates')

@pictureapp.route('/')
def index():
	#g.posts = Post.objects.all()
	return render_template('pictures.html')

xinganr/myapp/views/site.py
#!/usr/bin/env python
#-*-coding:utf-8-*-
from flask.ext.login import current_user
from flask import Blueprint, render_template,g
from myapp.forms.users import StatusForm
from config import POSTS_PER_PAGE
from myapp import db

import Image,ImageDraw,ImageFont
import random
import math, string  

siteapp=Blueprint("site", __name__,static_folder='static',template_folder='templates')

'''
@siteapp.before_request
def before_request():
    g.user = current_user
    if g.user.is_authenticated():

        db.session.add(g.user)
        db.session.commit()
        
'''


@siteapp.route('/',methods=['GET'])

def index():
	return render_template('index.html')

xinganr/myapp/views/user.py
#!/usr/bin/env python
#-*-coding:utf-8-*-
import logging
logger=logging.getLogger(__name__)

from flask import Flask,Blueprint,request,session,g,url_for,redirect,json,jsonify,abort
from flask import render_template,flash
from myapp.extensions import oid,oau,babel,pag
from flask import current_app as app 
from flask.ext import login
from flask.ext import wtf
from flask.ext.login import LoginManager,login_user,logout_user,current_user,login_required
from myapp.forms.users import *
#from config import posts_per_page,max_search_results
from myapp.utils.filters import *
#from myapp.utils.user import auth_user
from myapp.extensions import login_manager
from myapp import db
from datetime import datetime

from PIL import Image,ImageDraw,ImageFont
import sys,os

from myapp.models import User,Status,Log#,UserInfo,ROLE_USER,ROLE_ADMIN,Childinfo,Log,Comment,Picture,Category)
userapp=Blueprint("user",__name__,static_folder='static',template_folder='templates')

from werkzeug.utils import secure_filename


# Set this configuration to absolute or relative path to upload directory.



# statusupimg_path=''
# imgslist=[]

# @userapp.route('/save_statusupimg',methods=['GET','POST'])
# @login_required
# def save_statusupimg(filestorage, app=app):
#     "Save a Werkzeug file storage object to the upload folder."
#     global statusupimg_path
#     statusupimg_name = secure_filename(filestorage.filename)
#     statusupimg_path = os.path.join(app.config['UPLOAD_FOLDER'], statusupimg_name)
#     filestorage.save(statusupimg_path)
    

# @userapp.route('/save_statusupimgs',methods=['GET','POST'])
# @login_required
# def save_statusupimgs(request=request, app=app):
#     global imgslist
#     "Save all files in a request to the app's upload folder."
#     for _, filestorage in request.files.iteritems():
#         # Workaround: larger uploads cause a dummy file named '<fdopen>'.
#         # See the Flask mailing list for more information.
#         if filestorage.filename not in (None, 'fdopen', '<fdopen>'):
#             save_statusupimg(filestorage, app=app)
#             global statusupimg_path
#             print 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy' 
#             print statusupimg_path
#             imgslist.append(statusupimg_path)
#             print imgslist
#             print len(imgslist)
#     for x in len(imgslist):
#         imgsitem=jsonify(x=imgslist[x-1])
        
def save_file(filestorage, app=app):
    "Save a Werkzeug file storage object to the upload folder."
    filename = secure_filename(filestorage.filename)
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    filestorage.save(filepath)


def save_files(request=request, app=app):
    "Save all files in a request to the app's upload folder."
    for _, filestorage in request.files.iteritems():
        # Workaround: larger uploads cause a dummy file named '<fdopen>'.
        # See the Flask mailing list for more information.
        if filestorage.filename not in (None, 'fdopen', '<fdopen>'):
            save_file(filestorage, app=app)


    



class Anonymous(login.AnonymousUserMixin):
	user=User(email='',nickname=u'游客',password='',headimg='')

class LoginUser(login.UserMixin):
	"""Wraps User object  for Flask-Login"""
	def __init__(self,user):
	    self.id=user.id
	    self.user=user
            self.headimg=user.headimg

            #self.avatar=user.avatar(size)
            self.nickname=user.nickname

login_manager.login_view = 'user.login'
login_manager.login_message = u'需要登陆后才能访问本页'

#login_manager.anonymous_user=Anonymous


@login_manager.user_loader
def load_user(users_id):
    user=User.query.get(users_id)
    return user and LoginUser(user) or None
#def login_user(user, remember=False):
    """ 登陆用户并更新最近登陆时间 """
#    login.login_user(LoginUser(user),remember=False)
    #user.login_time = datetime.now()
'''
@userapp.before_request
def before_request():
    g.user = current_user
    if g.user.is_authenticated():
        #g.user.last_seen = datetime.now()
        db.session.add(g.user)
        db.session.commit()
        #g.search_form = SearchForm()
'''
 

#用户注册
@userapp.route('/signup',methods=['GET','POST'])
def signup():
	error=None
	next_url = request.args.get('next', url_for('site.index'))
	form = SignupForm(request.form,csrf_enabled=False)

        print 'bbbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!!!!!!!!!'
        print form.headimg

	#if current_user.is_authenticated():
	if current_user.is_authenticated():
		return redirect(url_for('user.userprofile'))

		#app.logger.info('request.form: ' + repr(request.values))
	
	#app.logger.info('>>> Signup user: ' + repr(dict(form.data, password='<MASK>',confirmpassword='<MASK>')))
    
            
	if form.validate_on_submit():
            f=request.files['headimg']
            f.save('/home/Alex/myproject/envflask/xinganr/myapp/static/headicon/%s' %form.user.nickname)
            fpath=('/static/headicon/%s' %form.user.nickname)
            user=User(email=form.email.data,nickname=form.nickname.data,password=form.password.data,headimg=fpath)
            db.session.add(user)
            db.session.commit()
	    flash(u'恭喜您！注册成功')
	    return redirect(url_for('user.login'))
        else:
            return render_template('signup.html',title=u'欢迎来到心肝儿网!',form=form)
'''

	if request.method=='POST':
		nickname=request.form.get('nickname').lower()
		email=request.form.get('email').lower()
		password=request.form.get('password')
		confirm_password=request.form.get('confirm_password')

		if not all([nickname,email,password,confirm_password]):
			error=u'请填满所有信息'
		elif password != confirm_password:
			error=u'密码不一致！请重新确认密码'
		elif User.query.filter_by(username=username).first:
			error=u'该用户名已被注册!'
		elif User.query.filter_by(email=email).first():
			error=u'该邮箱已被注册!'
		else:
			create_user(username,email,password)
			flash(u'恭喜您！注册成功')
			return redirect(url_for('user.login'))
        return render_template('signup.html',title=u'欢迎来到心肝儿网!',form=form,error=error)
'''


	
#用户登录
@userapp.route('/login',methods=['GET','POST'])
def login():
    error=None
    #user = User.query.filter_by(email = email).first()
    form = LoginForm(request.form, csrf_enabled=False)
    #user=form.user
    #form=LoginForm(request.form, csrf_enabled=False)
	#next_url=request.args.get('next',url_for('site.index'))
    
    #print form.validate_on_submit
    #if form.validate_on_submit():
    #form = LoginForm(request.form)
    #g.user=form.user

    #print form.validate()
    #print form.is_submitted()
    #print form.validate_on_submit()
    print form.errors
    #if g.user is not None and g.user.is_authenticated():
    #   return redirect(url_for('site.index'))
    
    if form.validate_on_submit():
        #session['remember_me'] = form.remember_me.data
        #user=User.query.get(users_email).first()
        login_user(form.user,remember=False)

        
        print form.user.is_active()
        print form.user.is_anonymous()
        
        flash(u'登录成功！')
        return redirect(url_for('site.index'))

    return render_template('login.html', title = u'欢迎来到心肝儿网!',form = form)
 
    def after_login(resp):
	#user=User.query.filter_by(email=resp.email).first():
	nickname=User.make_valid_nickname(nickname)
	nickname=User.make_unique_nickname(nickname)
	user=User(nickname=resp.nickname,email=resp.email)
        db.session.add(user)
        db.session.commit()
        login_user(user,remember=False)

    
   

'''
        flash("Success")
        return redirect(url_for("user.index"))
    return render_template("login.html", form=form)
'''
@userapp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.index'))

@userapp.route('/userprofile')		
@userapp.route('/userprofile/<nickname>')
@login_required
#@login_required
def userprofile(nickname=None):
    #user = User.query.filter_by(nickname=nickname).first()
    g.user=current_user
    print g.user.headimg
    return render_template('homepage.html')


@userapp.route('/account_edit',methods=['GET','POST'])
@login_required
def account_edit():
    error=None
    g.user=current_user
    form=AccountEditForm(request.form,csrf_enabled=False)
   #print form.FileField.has_file()

    print form.validate_on_submit()
    print form.errors
    if form.validate_on_submit():
        #filename=secure_filename(form.headimg.data.filename)
        headimages=request.files['headimg']
        db.session.add(headimg)
        db.session.commit()
        #form.populate_obj(g.user.headimg)
        return render_template('homepage.html')
    else:
        #filename=None
        return render_template('account_edit.html')
        
    return render_template('homepage.html',form=form)


@userapp.route('/status',methods=['GET','POST'])
@login_required
def status():
    error=None

    statuses=Status.query

    g.user=current_user
    ggg=g.user.nickname
    print ggg
    form=StatusForm(request.form,csrf_enabled=False)
    #if request.method=='POST':
        #f=request.files['body']
        #u=form.user.nickname
        #f.save('/home/Alex/myproject/envflask/xinganr/myapp/static/statusimg/%s' %g.user.nickname)
            
 

    #print form.errors
    print form.is_submitted()
    print form.validate_on_submit()
    print 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!!!!!!!!!!!!!!!'
    print form.errors
    #return render_template('status.html')
    


    if form.validate_on_submit():

        f=request.files['statusupimg']
        if f:
            f.save('/home/Alex/myproject/envflask/xinganr/myapp/static/pic/status/%s' %form.body.data[0:5])
            fpath=('/static/pic/status/%s' %form.body.data[0:5])
            status = Status(user_id=g.user.id,body=form.body.data,statusupimg=fpath,time=datetime.now())
        else:
            status = Status(user_id=g.user.id,body=form.body.data,time=datetime.now())
        
        print datetime.now()
        print '--------------------'

xinganr/myapp/templates/account_edit.html
{% extends "layout.html" %}
{% block content %}
<div>
	<form action="{{url_for('user.account_edit')}}" method="post" enctype="multipart/form-data">
		<label>
		<input id="headimg" name="headimg" type="file" value="请上传您的头像" tabindex="1"
	    </label>
	    </label>
		<input type="submit" value="提交"  id="button" class="btn-submit disabled" tabindex="2" />
	</label>
	</form>
{% endblock %}

xinganr/myapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% if title %}
	<title>{{title}}</title>
	{% else %}
	<title>Xinganr&middot;心肝儿网</title>
	{% endif %}

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            
            {% for message in messages %}
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            
        {% endif %}
	<!-- 添加页面图标icon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='heart.ico') }}">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="xinganr,心肝儿,心肝儿网,社区,组群"/>
	<meta name="description" content="心肝儿网是记录您宝贝成长历程中的生活点滴的社交网站" />
	<meta name="author" content="xinganr心肝儿网">
	<!-- Add jQuery library -->
	<script src="/static/js/jquery-1.8.3.min.js" type="text/javascript"></script>

	<!-- Add bootstrap library -->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/static/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<script src="/static/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- Add bootstrap hover-dropdown -->
	<script src="/static/js/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
	<!-- Add lettering logo-->
	<script src="/static/js/jquery.lettering-0.6.1.min.js" type="text/javascript"></script>

	<!-- Add waterfall library -->
	<script src="/static/js/waterfall.js" type="text/javascript"></script>

	<!-- Add index index 本地 -->
	<link href="/static/css/index.css" rel="stylesheet" />
	<script src="/static/js/my.js" type="text/javascript"></script>

	<!-- Add mCustomScrollbar diary-->
	<link href="/static/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
	<script src="/static/js/jquery.mCustomScrollbar.concat.min.js" type="text/javascript"></script>

	<!-- Add Font Awesom图标字体 -->
	<link href="/static/css/font-awesome.min.css" rel="stylesheet" />

	<!-- Add ckeditor diary-edit-->
	<script type="text/javascript" src="/static/ckeditor/ckeditor.js"></script>

	<!-- Add book diary -->
	<link rel="stylesheet" type="text/css" href="/static/css/book2.css" />
	<script src="/static/js/modernizr.custom.js"></script>
	
	<!--气泡提示 index -->
	<link rel="stylesheet" type="text/css" href="/static/css/grumble.css?v=1" />
	<script type="text/javascript" src="/static/js/Bubble.js"></script>
	<script type="text/javascript" src="/static/js/jquery.grumble.min.js"></script>

	<!-- 表情 -->
	<script type="text/javascript" src="/static/js/face.js" charset="utf-8"></script>

	<script type=text/javascript>
	    var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
	</script>

	<!--uploadify-->
    <script type="text/javascript" src="/static/js/jquery.uploadify.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/uploadify.css" />
    <script type="text/javascript" src="/static/js/swfobject.js"></script>



</head>
<body>
	<div class="header">
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="logo pull-left" href="{{url_for('site.index')}}">
						<span class="char1">X</span>
					 	<span class="char2">i</span>
					 	<span class="char3">n</span>
					 	<span class="char4">g</span>
					 	<span class="char5">a</span>
					 	<span class="char6">n</span>
					 	<span class="char7">r</span>
					</a>
					<div class="pull-right">
						<ul class="nav">

							<li><a href="#" id="gift"><i class="icon-gift icon-large icon-muted"></i></a></li>
							<!-- <li><a href="#" class="logged">登录</a></li> -->
							<li class="dropdown"><a href="{{url_for('user.login')}}" class="dropdown-toggle hover" data-toggle="dropdown"><img id="customer_headimg_thumb" src="" /><lable id="customer_nickname"></lable><b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="{{ url_for('user.userprofile') }}"><i class="icon-flag"></i> 我的心肝儿</a></li>
									<li><a href="/help/support"><i class="icon-envelope-alt"></i> 消息<span class="badge badge-warning pull-right">4</span></a></li>
									<li><a href="{{ url_for('user.account_edit') }}"><i class="icon-cog"></i> 设置</a></li>
									<li class="divider"></li>
									<li><a href="{{url_for('user.logout')}}"><i class="icon-off"></i> 退出</a></li>
								</ul>
							</li>
						</ul>
					</div>
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li><a href="{{url_for('site.index')}}"><i class="icon-home"></i> 首页</a></li>
							<li class="active"><a href="{{url_for('user.news')}}"><i class="icon-globe"></i> 动态</a></li>
							<li><a href="#"><i class="icon-book"></i> 日记</a></li>
							<li><a href="#"><i class="icon-qrcode"></i> 问答</a></li>
							<li><a href="#"><i class="icon-coffee"></i> 兴趣</a></li>
						</ul>
						<div class="navbar-search input-append">
							<input type="text" class="span2" placeholder="搜索">
  							<button type="submit" class="btn"><i class="icon-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>


{% endwith %}
{% block content %}{% endblock %}

xinganr/myapp/templates/layout_old.html
<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	{% if title %}
	<title>{{title}}</title>
	{% else %}
	<title>Xinganr&middot;心肝儿网</title>
	{% endif %}

    <!-- 添加页面图标icon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='heart.ico') }}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="xinganr,心肝儿,心肝儿网,麻麻,孕婴,育儿社区,辣妈,组群"/>
	<meta name="description" content="心肝儿网是记录您宝贝成长历程中的生活点滴的社交网站" />
	<meta name="author" content="xinganr心肝儿网">

		<!-- Add jQuery library -->
	<script src="../static/js/jquery-1.9.1.min.js" type="text/javascript"></script>

	<!-- Add bootstrap library -->
	<link href="../static/css/bootstrap.min.css" rel="stylesheet" />
	<link href="../static/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<script src="../static/js/bootstrap.min.js" type="text/javascript"></script>

	<!-- Add lettering logo-->
	<script src="../static/js/jquery.lettering-0.6.1.min.js" type="text/javascript"></script>

	<!-- Add waterfall library -->
	<script src="../static/js/waterfall.js" type="text/javascript"></script>

	<!-- Add handlebars template js模板-->
	<script src="../static/js/handlebars-1.0.rc.1.js" type="text/javascript"></script>


	<!-- Add index index 本地 -->
	<link href="../static/css/index.css" rel="stylesheet" />
	
	
	<script src="../static/js/status.js" type="text/javascript"></script>


	<!-- Add ruler 页面像素尺 -->
	<!--
	<link href="http://www.zhangxinxu.com/study/css/ruler.css" rel="stylesheet" />
	<script src="http://www.zhangxinxu.com/study/js/jquery.zxxPageRuler.1.1.js" type="text/javascript"></script>
	-->

	<!-- Add mCustomScrollbar -->
	<link href="../static/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
	<script src="../static/js/jquery.mCustomScrollbar.concat.min.js" type="text/javascript"></script>

	<!-- Add Font Awesom图标字体 -->
	<link href="../static/css/font-awesome.min.css" rel="stylesheet" />

	<!--momentjs-->
	<script src="../static/js/moment.min.js"></script>

</head>

<body>
	<div class="header">
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="logo pull-left" href="{{url_for('site.index')}}">
						<span class="char1">X</span>
					 	<span class="char2">i</span>
					 	<span class="char3">n</span>
					 	<span class="char4">g</span>
					 	<span class="char5">a</span>
					 	<span class="char6">n</span>
					 	<span class="char7">r</span>
					</a>
					<div class="pull-right">
						<div class="btn-group ">
							<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
							    上传
							    <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="icon-picture"></i> 照片</a></li>
								<li><a href="#"><i class="icon-list-alt"></i> 文字</a></li>
								<li><a href="#"><i class="icon-music"></i> 音乐</a></li>
								<li class="disabled"><a href="#"><i class="icon-film"></i> 视频</a></li>
							</ul>
						</div>
						<a href="{{url_for('user.login')}}" class="btn btn-success">登录</a>
						<a href="{{url_for('user.signup')}}" class="btn btn-warning">注册</a>
					</div>
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li class="active"><a href="{{url_for('site.index')}}"><i class="icon-home"></i> 首页</a></li>
							<li><a href="{{url_for('picture.index')}}"><i class="icon-picture"></i> 相片</a></li>
							<li><a href="{{url_for('user.status')}}"><i class="icon-bookmark"></i> 新鲜事</a></li>
							
							<li><a href="{{url_for('user.userprofile')}}"><i class="icon-heart"></i> 我的心肝儿</a></li>
							
						</ul>
						<div class="navbar-search input-append">
							<input class="span2" id="appendedInput" type="text" placeholder="搜索">
							<a type="submit" class="add-on" id="appendedInput" style="cursor:pointer"><i class="icon-search"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- header end -->



{% block content %}{% endblock %}

xinganr/myapp/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="main">
		<div class="container">
			<div class="row-fluid">
				<div class="span4">
					<div class="login-ex">
						<div>你还可以用第三方帐号登录</div>
						<a href="#" class="login-sina">
							<img src="../static/images/sina.png" alt=""><span>新浪微博登录</span>
						</a>
						<a href="#" class="login-douban">
							<img src="../static/images/dou.png" alt=""><span>豆瓣账号登录</span>
						</a>
						<a href="#" class="login-renren">
							<img src="../static/images/renren.png" alt=""><span>人人账号登录</span>
						</a>
						<div><span>还没有帐号？</span><a href="{{url_for('user.signup')}}">马上注册</a></div>
					</div>
				</div>
				<div class="span8">
					<div class="login">
						<h3>欢迎登录心肝儿</h3>
						<div class="alert alert-error">
							<a class="close" data-dismiss="alert" href="#">×</a>邮箱或密码错误!
						</div>
						<form action="{{ url_for('user.login') }}" name="login" method="post">
                            {{form.csrf_token}}
							<input type="text" id="email" name="email" placeholder="邮箱" class="input-xlarge">
							<input type="password" id="password" name="password" placeholder="密码" class="input-xlarge">
							<label class="checkbox"> 
								<input type="checkbox" checked>下次自动登录
							</label>
							<button type="submit" class="btn btn-success">登录</button>
							<a class="forget" href="#">忘记密码?</a>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

xinganr/myapp/templates/pictures.html
{% extends "layout.html" %}

xinganr/myapp/templates/signup_old.html
{% extends "layout.html" %}

{% block content %}
<<div class="main">
    <div class="container">
       
        <div class="row-fluid">
            <div class="span9"> 
                <div id="signup">
                    <h1>欢迎加入心肝儿</h1>

                    <div class="grid-16-8 clearfix">

                        <div class="article">

                            <form action="{{ url_for('user.signup') }}" name="signup" method="post" enctype="multipart/form-data">

                                <div style="display:none;">
                                    <input type="hidden" name="source" value="simple"/>
                                    <input type="hidden" name="redir" value=""/>
                                    <!--<img src="https://www.douban.com/pics/blank.gif"   onload="loadTestImage('https://www.douban.com/accounts/register')"/> -->
                                </div>
                                <div class="item extra-tips">
                                    <label>昵称</label>
                                    <input id="nickname" name="nickname" type="text" class="basic-input" maxlength="15" tabindex="1" value=""/>
                                </div>
                                <!--<div class="suggestion">
                                    <span class="tips">第一印象很重要，起个响亮的名号吧</span>
                                </div>
                                -->
                                <div class="item extra-tips">
                                    <label>邮箱</label>
                                    <input id="email" name="email" type="text" class="basic-input" maxlength="60" tabindex="2" value=""/>
                                </div>
                                <div class="suggestion">
                                    <div id="email_suggestion"></div>
                                </div>
                                <div class="item extra-tips">
                                    <label>密码</label>
                                    <input id="password" name="password" type="password" class="basic-input" tabindex="3" maxlength="20"/>
                                </div>
                                
                                <div class="item extra-tips">
                                    <label>确认密码</label>
                                    <input id="password" name="confirm_password" type="password" class="basic-input" tabindex="4" maxlength="20"/>
                                </div>
                                
                                <div class="item extra-tips">
                                    <label>headimg</label>
                                    <input id="headimg" name="headimg" type="file" class="basic-input" tabindex="5" />
                                </div>

                                <div class="item loc-item">
                                    <label>常居地</label>
                                    <span class="loc">
                                        <em id="location">心肝儿猜你在<strong>西安</strong>，没猜对？</em> <a href="#" class="a-btn-location" id="edloc">手动选择</a>
                                    </span>

                                    <input type="hidden" name="loc" value="118371"/>
                                </div>

                                <div class="item captcha-item">
                                    <label>验证码</label>
                                    <p><img src="http://www.douban.com/misc/captcha?id=d1CraRsJt2zVsbXyvToYgsBa&amp;size=s" class="captcha-img"/><span class="tips">看不清？<a href="" id="cap_resend">换一个</a></span></p>
                                    
                                    <input type="text" name="captcha-solution" class="basic-input captcha" id="captcha" tabindex="4" maxlength="10"/>
                                    <input type="hidden" value="d1CraRsJt2zVsbXyvToYgsBa" name="captcha-id">

                                    <span class="validate-error" id="frm_error"></span>
                                </div>

                                <div class="item">
                                    <p class="agreement">
                                        <label for="agreement" class="agreement-label">
                                            <input type="checkbox" id="agreement" name="form_agreement" tabindex/>我已经认真阅读并同意心肝儿的《<a target="_blank" href="/about?policy=agreement">使用协议</a>》。
                                        </label>
                                    </p>
                                </div>
                                <div class="item-submit">
                                    <label>&nbsp;</label>
                                    <input type="submit" value="注册"  id="button" class="btn-submit disabled" tabindex="6" title="阅读并同意心肝儿的《使用协议》方可注册。"/>
                                </div>
                            </form>
                        </div>
                        <div class="aside">
                            <p class="pl">&gt;&nbsp;已经拥有心肝儿帐号? <a rel="nofollow" href="{{ url_for('user.login') }}">直接登录</a></p>
                        </div>
                        <div class="extra">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

xinganr/myapp/templates/xinmail.html
{% extends "layout.html" %}
{% block content %}
<div><h2><strong>我的心邮</strong></h2>
</div>
{% endblock %}